// ============================================================
// AUTO CORE — Sample Automotive Data
// ============================================================
import type { Product, Category, Brand, BlogPost, DealProduct, BannerSlide } from "./types";

// ── CATEGORIES ──────────────────────────────────────────────
export const categories: Category[] = [
  {
    id: "cat-01",
    name: "Engine Parts",
    slug: "engine-parts",
    description: "Pistons, gaskets, timing belts, oil pumps, and more",
    icon: "⚙️",
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&h=300&fit=crop&q=80",
    productCount: 1240,
    parentId: undefined,
  },
  {
    id: "cat-02",
    name: "Brake System",
    slug: "brake-system",
    description: "Brake pads, rotors, calipers, lines, and brake fluid",
    icon: "🛑",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&q=80",
    productCount: 870,
    parentId: undefined,
  },
  {
    id: "cat-03",
    name: "Suspension",
    slug: "suspension",
    description: "Shocks, struts, control arms, bushings, and sway bars",
    icon: "🔩",
    image: "https://images.unsplash.com/photo-1565689157206-0fddef7589a2?w=400&h=300&fit=crop&q=80",
    productCount: 650,
    parentId: undefined,
  },
  {
    id: "cat-04",
    name: "Electrical",
    slug: "electrical",
    description: "Alternators, starters, batteries, sensors, and wiring",
    icon: "⚡",
    image: "https://images.unsplash.com/photo-1558618047-f2b4ed8a0b46?w=400&h=300&fit=crop&q=80",
    productCount: 980,
    parentId: undefined,
  },
  {
    id: "cat-05",
    name: "Wheels & Tires",
    slug: "wheels-tires",
    description: "Alloy wheels, steel rims, all-season and performance tires",
    icon: "🔘",
    image: "https://images.unsplash.com/photo-1584727638096-042c45049ebe?w=400&h=300&fit=crop&q=80",
    productCount: 520,
    parentId: undefined,
  },
  {
    id: "cat-06",
    name: "Filters",
    slug: "filters",
    description: "Oil filters, air filters, fuel filters, cabin filters",
    icon: "🔧",
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=300&fit=crop&q=80",
    productCount: 430,
    parentId: undefined,
  },
  {
    id: "cat-07",
    name: "Lighting",
    slug: "lighting",
    description: "Headlights, tail lights, LED upgrades, fog lights",
    icon: "💡",
    image: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=400&h=300&fit=crop&q=80",
    productCount: 360,
    parentId: undefined,
  },
  {
    id: "cat-08",
    name: "Body Parts",
    slug: "body-parts",
    description: "Bumpers, fenders, hoods, mirrors, and body panels",
    icon: "🚗",
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&h=300&fit=crop&q=80",
    productCount: 720,
    parentId: undefined,
  },
  {
    id: "cat-09",
    name: "Cooling System",
    slug: "cooling-system",
    description: "Radiators, water pumps, thermostats, coolant hoses",
    icon: "🌡️",
    image: "https://images.unsplash.com/photo-1582560475093-ba66accbc424?w=400&h=300&fit=crop&q=80",
    productCount: 280,
    parentId: undefined,
  },
  {
    id: "cat-10",
    name: "Transmission",
    slug: "transmission",
    description: "Clutch kits, gear sets, torque converters, differentials",
    icon: "🔄",
    image: "https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=400&h=300&fit=crop&q=80",
    productCount: 310,
    parentId: undefined,
  },
  {
    id: "cat-11",
    name: "Accessories",
    slug: "accessories",
    description: "Floor mats, seat covers, dash kits, cargo organizers",
    icon: "🎛️",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=300&fit=crop&q=80",
    productCount: 890,
    parentId: undefined,
  },
  {
    id: "cat-12",
    name: "Other Parts",
    slug: "other-parts",
    description: "Exhaust systems, fuel systems, HVAC, and more",
    icon: "🔨",
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=300&fit=crop&q=80",
    productCount: 540,
    parentId: undefined,
  },
];

// ── BRANDS ───────────────────────────────────────────────────
export const brands: Brand[] = [
  { id: "br-01", name: "Bosch", slug: "bosch", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Bosch-logo.svg/320px-Bosch-logo.svg.png", description: "German engineering excellence", country: "Germany", productCount: 1820, isFeatured: true },
  { id: "br-02", name: "ACDelco", slug: "acdelco", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/ACDelco_logo.svg/320px-ACDelco_logo.svg.png", description: "OEM quality replacement parts", country: "USA", productCount: 1540, isFeatured: true },
  { id: "br-03", name: "Denso", slug: "denso", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/DENSO_logo.svg/320px-DENSO_logo.svg.png", description: "Japanese precision components", country: "Japan", productCount: 980, isFeatured: true },
  { id: "br-04", name: "Monroe", slug: "monroe", logo: "https://via.placeholder.com/160x60/0d0d0d/d4f000?text=MONROE", description: "Suspension and ride control", country: "USA", productCount: 420, isFeatured: true },
  { id: "br-05", name: "Brembo", slug: "brembo", logo: "https://via.placeholder.com/160x60/cc0000/ffffff?text=BREMBO", description: "Premium braking systems", country: "Italy", productCount: 380, isFeatured: true },
  { id: "br-06", name: "K&N", slug: "kn", logo: "https://via.placeholder.com/160x60/e63946/ffffff?text=K%26N", description: "High-performance air filters", country: "USA", productCount: 290, isFeatured: true },
  { id: "br-07", name: "NGK", slug: "ngk", logo: "https://via.placeholder.com/160x60/1a1a1a/ffffff?text=NGK", description: "Spark plugs and ignition", country: "Japan", productCount: 350, isFeatured: false },
  { id: "br-08", name: "Moog", slug: "moog", logo: "https://via.placeholder.com/160x60/003087/ffffff?text=MOOG", description: "Chassis and steering parts", country: "USA", productCount: 460, isFeatured: false },
];

// ── PRODUCTS ─────────────────────────────────────────────────
export const products: Product[] = [
  {
    id: "prod-001",
    name: "Bosch QuietCast Premium Brake Pad Set",
    slug: "bosch-quietcast-premium-brake-pad-set",
    brand: "Bosch",
    sku: "BSH-BC905",
    category: "Brake System",
    subcategory: "Brake Pads",
    description: "Bosch QuietCast Premium ceramic brake pads deliver quiet, clean braking performance. Features multi-layer shim for noise reduction and chamfered/slotted design for improved pad break-in. Fits most domestic and import vehicles.",
    shortDescription: "Premium ceramic brake pads with multi-layer noise reduction shim.",
    price: 42.99,
    originalPrice: 58.99,
    discountPercent: 27,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop&q=80",
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80",
    rating: 4.8,
    reviewCount: 312,
    stock: 84,
    stockStatus: "in_stock",
    tags: ["brakes", "ceramic", "quiet", "premium"],
    compatibility: [
      { make: "Toyota", model: "Camry", yearFrom: 2018, yearTo: 2024 },
      { make: "Honda", model: "Accord", yearFrom: 2017, yearTo: 2024 },
      { make: "Ford", model: "Fusion", yearFrom: 2016, yearTo: 2022 },
    ],
    specifications: { Material: "Ceramic", "Axle Position": "Front", "Pad Count": "4 Pads", "Shim Type": "Multi-layer" },
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-002",
    name: "K&N High-Flow Performance Air Filter",
    slug: "kn-high-flow-performance-air-filter",
    brand: "K&N",
    sku: "KN-33-2304",
    category: "Filters",
    subcategory: "Air Filters",
    description: "K&N high-flow air filters are washable and reusable, providing increased horsepower and acceleration. The layered oiled cotton gauze media provides outstanding filtration while minimizing airflow restriction.",
    shortDescription: "Washable, reusable high-flow air filter for increased horsepower.",
    price: 54.99,
    originalPrice: undefined,
    discountPercent: undefined,
    images: [
      "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=400&fit=crop&q=80",
    rating: 4.7,
    reviewCount: 189,
    stock: 52,
    stockStatus: "in_stock",
    tags: ["filter", "performance", "washable", "horsepower"],
    compatibility: [
      { make: "Ford", model: "F-150", yearFrom: 2015, yearTo: 2024 },
      { make: "Chevrolet", model: "Silverado", yearFrom: 2014, yearTo: 2024 },
    ],
    specifications: { Media: "Oiled Cotton Gauze", "Filter Type": "Panel", Washable: "Yes", "Service Miles": "50,000" },
    isFeatured: true,
    isOnSale: false,
    isNew: false,
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-003",
    name: "Monroe OESpectrum Strut Assembly",
    slug: "monroe-oespectrum-strut-assembly",
    brand: "Monroe",
    sku: "MNR-172631",
    category: "Suspension",
    subcategory: "Struts",
    description: "Monroe OESpectrum strut assemblies are engineered to restore original handling and ride control. Complete assembly includes spring, mount, and bearing plate for quick, easy installation.",
    shortDescription: "Complete strut assembly for OE-quality ride restoration.",
    price: 129.99,
    originalPrice: 159.99,
    discountPercent: 19,
    images: [
      "https://images.unsplash.com/photo-1565689157206-0fddef7589a2?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1565689157206-0fddef7589a2?w=400&h=400&fit=crop&q=80",
    rating: 4.6,
    reviewCount: 97,
    stock: 23,
    stockStatus: "low_stock",
    tags: ["suspension", "strut", "ride-control", "complete-assembly"],
    compatibility: [
      { make: "Toyota", model: "Corolla", yearFrom: 2019, yearTo: 2024 },
      { make: "Toyota", model: "Camry", yearFrom: 2018, yearTo: 2024 },
    ],
    specifications: { "Assembly Type": "Complete", Position: "Front Left", "Spring Included": "Yes", "Mount Included": "Yes" },
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-004",
    name: "Denso Heavy-Duty Alternator",
    slug: "denso-heavy-duty-alternator",
    brand: "Denso",
    sku: "DNS-210-0396",
    category: "Electrical",
    subcategory: "Alternators",
    description: "Denso remanufactured alternators are built to original equipment specifications using new internal components. 100% electrical testing ensures maximum performance and reliability.",
    shortDescription: "OE-spec remanufactured alternator with 100% electrical testing.",
    price: 189.99,
    originalPrice: undefined,
    discountPercent: undefined,
    images: [
      "https://images.unsplash.com/photo-1558618047-f2b4ed8a0b46?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1558618047-f2b4ed8a0b46?w=400&h=400&fit=crop&q=80",
    rating: 4.9,
    reviewCount: 64,
    stock: 15,
    stockStatus: "low_stock",
    tags: ["electrical", "alternator", "remanufactured", "heavy-duty"],
    compatibility: [
      { make: "Honda", model: "Civic", yearFrom: 2016, yearTo: 2021 },
      { make: "Honda", model: "CR-V", yearFrom: 2017, yearTo: 2022 },
    ],
    specifications: { Amperage: "110A", Voltage: "12V", Type: "Remanufactured", Warranty: "1 Year" },
    isFeatured: true,
    isOnSale: false,
    isNew: true,
    createdAt: "2024-08-20T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-005",
    name: "Brembo Sport Drilled & Slotted Brake Rotor",
    slug: "brembo-sport-drilled-slotted-brake-rotor",
    brand: "Brembo",
    sku: "BRM-09A90011",
    category: "Brake System",
    subcategory: "Brake Rotors",
    description: "Brembo Sport drilled and slotted rotors deliver maximum braking performance for street and track applications. The UV-coated finish prevents corrosion and extends service life.",
    shortDescription: "Premium drilled & slotted sport brake rotor with UV coating.",
    price: 94.99,
    originalPrice: 124.99,
    discountPercent: 24,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80",
    rating: 4.9,
    reviewCount: 218,
    stock: 38,
    stockStatus: "in_stock",
    tags: ["brakes", "rotors", "drilled", "slotted", "sport", "performance"],
    compatibility: [
      { make: "BMW", model: "3 Series", yearFrom: 2019, yearTo: 2024 },
      { make: "Audi", model: "A4", yearFrom: 2017, yearTo: 2024 },
    ],
    specifications: { Type: "Drilled & Slotted", Material: "Cast Iron", "Coating": "UV Painted", Diameter: "330mm" },
    isFeatured: true,
    isOnSale: true,
    isNew: false,
    createdAt: "2024-04-10T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-006",
    name: "Bosch Platinum +4 Spark Plug Set",
    slug: "bosch-platinum-4-spark-plug-set",
    brand: "Bosch",
    sku: "BSH-4304",
    category: "Engine Parts",
    subcategory: "Spark Plugs",
    description: "Bosch Platinum +4 spark plugs feature four yttrium-enhanced ground electrodes for a complete 360° ignition. Platinum center electrode delivers longer life and consistent performance.",
    shortDescription: "4-electrode platinum spark plugs for 360° ignition coverage.",
    price: 32.99,
    originalPrice: undefined,
    discountPercent: undefined,
    images: [
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&h=400&fit=crop&q=80",
    rating: 4.7,
    reviewCount: 445,
    stock: 120,
    stockStatus: "in_stock",
    tags: ["engine", "spark-plugs", "platinum", "ignition"],
    compatibility: [
      { make: "Ford", model: "F-150", yearFrom: 2011, yearTo: 2020 },
      { make: "Chevrolet", model: "Silverado", yearFrom: 2010, yearTo: 2019 },
    ],
    specifications: { Material: "Platinum", Electrodes: "4", "Thread Size": "14mm", "Reach": "19mm" },
    isFeatured: false,
    isOnSale: false,
    isNew: false,
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-007",
    name: "ACDelco Professional Serpentine Belt",
    slug: "acdelco-professional-serpentine-belt",
    brand: "ACDelco",
    sku: "ACD-6K930",
    category: "Engine Parts",
    subcategory: "Belts",
    description: "ACDelco Professional serpentine belts are manufactured to OE specifications for a precise fit. EPDM construction resists heat, oil, and ozone for long service life.",
    shortDescription: "OE-spec EPDM serpentine belt for reliable engine accessory drive.",
    price: 24.99,
    originalPrice: 34.99,
    discountPercent: 29,
    images: [
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&h=400&fit=crop&q=80",
    rating: 4.5,
    reviewCount: 178,
    stock: 67,
    stockStatus: "in_stock",
    tags: ["engine", "belt", "serpentine", "EPDM"],
    compatibility: [
      { make: "Chevrolet", model: "Malibu", yearFrom: 2016, yearTo: 2022 },
      { make: "GMC", model: "Terrain", yearFrom: 2016, yearTo: 2021 },
    ],
    specifications: { Material: "EPDM", Width: "25.4mm", Length: "930mm", Ribs: "6" },
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    createdAt: "2024-02-25T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-008",
    name: "NGK Iridium IX Spark Plug",
    slug: "ngk-iridium-ix-spark-plug",
    brand: "NGK",
    sku: "NGK-6619",
    category: "Engine Parts",
    subcategory: "Spark Plugs",
    description: "NGK Iridium IX spark plugs provide superior ignitability, higher firing efficiency, and improved throttle response. Fine-wire iridium center electrode lasts up to 3x longer than standard plugs.",
    shortDescription: "Fine-wire iridium spark plug for superior ignition performance.",
    price: 14.99,
    originalPrice: undefined,
    discountPercent: undefined,
    images: [
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&h=400&fit=crop&q=80",
    rating: 4.8,
    reviewCount: 632,
    stock: 200,
    stockStatus: "in_stock",
    tags: ["engine", "spark-plugs", "iridium", "performance"],
    compatibility: [
      { make: "Toyota", model: "Camry", yearFrom: 2012, yearTo: 2024 },
      { make: "Honda", model: "Accord", yearFrom: 2013, yearTo: 2024 },
      { make: "Nissan", model: "Altima", yearFrom: 2013, yearTo: 2022 },
    ],
    specifications: { Material: "Iridium", Electrodes: "1", "Thread Size": "14mm", "Projected Type": "Yes" },
    isFeatured: true,
    isOnSale: false,
    isNew: false,
    createdAt: "2024-01-05T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-009",
    name: "Bosch OE Oxygen Sensor",
    slug: "bosch-oe-oxygen-sensor",
    brand: "Bosch",
    sku: "BSH-15717",
    category: "Electrical",
    subcategory: "Sensors",
    description: "Bosch OE-style oxygen sensors restore precise fuel mixture control for improved fuel economy and lower emissions. Laser-welded body withstands extreme engine heat.",
    shortDescription: "OE-style O2 sensor for improved fuel economy and emissions.",
    price: 47.99,
    originalPrice: 62.99,
    discountPercent: 24,
    images: [
      "https://images.unsplash.com/photo-1558618047-f2b4ed8a0b46?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1558618047-f2b4ed8a0b46?w=400&h=400&fit=crop&q=80",
    rating: 4.6,
    reviewCount: 143,
    stock: 45,
    stockStatus: "in_stock",
    tags: ["electrical", "sensor", "oxygen", "emissions", "fuel-economy"],
    compatibility: [
      { make: "Toyota", model: "4Runner", yearFrom: 2010, yearTo: 2023 },
      { make: "Toyota", model: "Tacoma", yearFrom: 2005, yearTo: 2023 },
    ],
    specifications: { Wires: "4-Wire", "Sensor Type": "Wideband", Thread: "18mm x 1.5", Length: "36\"" },
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    createdAt: "2024-03-15T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-010",
    name: "Moog Front Lower Ball Joint",
    slug: "moog-front-lower-ball-joint",
    brand: "Moog",
    sku: "MG-K80631",
    category: "Suspension",
    subcategory: "Ball Joints",
    description: "Moog Problem Solver ball joints feature a gusher bearing design that allows grease to flow to the areas of highest wear under all operating conditions. Meets or exceeds OE specifications.",
    shortDescription: "Problem Solver ball joint with gusher bearing for maximum wear life.",
    price: 38.99,
    originalPrice: undefined,
    discountPercent: undefined,
    images: [
      "https://images.unsplash.com/photo-1565689157206-0fddef7589a2?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1565689157206-0fddef7589a2?w=400&h=400&fit=crop&q=80",
    rating: 4.7,
    reviewCount: 256,
    stock: 58,
    stockStatus: "in_stock",
    tags: ["suspension", "ball-joint", "front", "lower", "steering"],
    compatibility: [
      { make: "Ford", model: "F-150", yearFrom: 2004, yearTo: 2020 },
      { make: "Ford", model: "Explorer", yearFrom: 2002, yearTo: 2010 },
    ],
    specifications: { Position: "Front Lower", Type: "Greaseable", Material: "Forged Steel", Warranty: "Limited Lifetime" },
    isFeatured: false,
    isOnSale: false,
    isNew: false,
    createdAt: "2024-04-01T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-011",
    name: "Denso Cabin Air Filter",
    slug: "denso-cabin-air-filter",
    brand: "Denso",
    sku: "DNS-453-6002",
    category: "Filters",
    subcategory: "Cabin Air Filters",
    description: "Denso cabin air filters trap pollen, dust, and other contaminants to keep the air inside your vehicle clean. Activated charcoal layer eliminates odors.",
    shortDescription: "Activated charcoal cabin air filter for clean, odor-free interior air.",
    price: 18.99,
    originalPrice: 24.99,
    discountPercent: 24,
    images: [
      "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=400&fit=crop&q=80",
    rating: 4.5,
    reviewCount: 387,
    stock: 145,
    stockStatus: "in_stock",
    tags: ["filter", "cabin", "air-quality", "charcoal"],
    compatibility: [
      { make: "Toyota", model: "RAV4", yearFrom: 2019, yearTo: 2024 },
      { make: "Toyota", model: "Highlander", yearFrom: 2020, yearTo: 2024 },
    ],
    specifications: { Media: "Activated Charcoal", Dimensions: "10.5\" x 9.2\"", "Micron Rating": "0.3", "MERV Rating": "13" },
    isFeatured: false,
    isOnSale: true,
    isNew: false,
    createdAt: "2024-05-10T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
  {
    id: "prod-012",
    name: "ACDelco Engine Oil Filter",
    slug: "acdelco-engine-oil-filter",
    brand: "ACDelco",
    sku: "ACD-PF64",
    category: "Filters",
    subcategory: "Oil Filters",
    description: "ACDelco Professional oil filters feature a high-capacity media for optimal filtration, a drain-back valve to prevent dry start, and a steel case for enhanced durability.",
    shortDescription: "High-capacity oil filter with anti-drain-back valve.",
    price: 8.99,
    originalPrice: undefined,
    discountPercent: undefined,
    images: [
      "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&h=600&fit=crop&q=80",
    ],
    thumbnail: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=400&fit=crop&q=80",
    rating: 4.6,
    reviewCount: 821,
    stock: 320,
    stockStatus: "in_stock",
    tags: ["filter", "oil", "engine", "maintenance"],
    compatibility: [
      { make: "Chevrolet", model: "Silverado", yearFrom: 2007, yearTo: 2024 },
      { make: "GMC", model: "Sierra", yearFrom: 2007, yearTo: 2024 },
      { make: "Chevrolet", model: "Equinox", yearFrom: 2010, yearTo: 2024 },
    ],
    specifications: { "Thread Size": "22mm x 1.5", "Anti-Drain Valve": "Yes", "By-Pass Valve": "Yes", Height: "4.5\"" },
    isFeatured: false,
    isOnSale: false,
    isNew: false,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-10-01T10:00:00Z",
  },
];

// ── DEALS OF THE WEEK ────────────────────────────────────────
export const dealsOfTheWeek: DealProduct[] = [
  {
    product: products[0], // Bosch Brake Pads
    dealPrice: 34.99,
    dealEndsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    savings: 24.00,
  },
  {
    product: products[4], // Brembo Rotor
    dealPrice: 79.99,
    dealEndsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    savings: 45.00,
  },
  {
    product: products[2], // Monroe Strut
    dealPrice: 109.99,
    dealEndsAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    savings: 50.00,
  },
  {
    product: products[6], // ACDelco Belt
    dealPrice: 19.99,
    dealEndsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    savings: 15.00,
  },
];

// ── BLOG POSTS ───────────────────────────────────────────────
export const blogPosts: BlogPost[] = [
  {
    id: "blog-01",
    title: "How to Choose the Right Brake Pads for Your Vehicle",
    slug: "how-to-choose-right-brake-pads",
    excerpt: "Not all brake pads are created equal. Learn the key differences between ceramic, semi-metallic, and organic brake pads to find the best fit for your driving style.",
    content: "",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop&q=80",
    author: { id: "auth-01", name: "Marcus Reed", avatar: "https://randomuser.me/api/portraits/men/32.jpg", role: "Auto Tech Specialist" },
    category: "Maintenance",
    tags: ["brakes", "maintenance", "buying-guide"],
    publishedAt: "2024-09-15T10:00:00Z",
    readTime: 6,
  },
  {
    id: "blog-02",
    title: "Top 7 Signs Your Suspension Needs Attention",
    slug: "signs-your-suspension-needs-attention",
    excerpt: "Unusual noises, pulling to one side, and rough rides are all red flags. Discover the warning signs of worn suspension components before they become a safety issue.",
    content: "",
    image: "https://images.unsplash.com/photo-1565689157206-0fddef7589a2?w=800&h=500&fit=crop&q=80",
    author: { id: "auth-02", name: "Sara Elkins", avatar: "https://randomuser.me/api/portraits/women/44.jpg", role: "Automotive Engineer" },
    category: "Safety",
    tags: ["suspension", "safety", "inspection"],
    publishedAt: "2024-09-20T10:00:00Z",
    readTime: 5,
  },
  {
    id: "blog-03",
    title: "Engine Oil Filter: Why It Matters More Than You Think",
    slug: "engine-oil-filter-why-it-matters",
    excerpt: "The humble oil filter does critical work protecting your engine. Here's what happens when it's neglected and how often you should really be changing it.",
    content: "",
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&h=500&fit=crop&q=80",
    author: { id: "auth-01", name: "Marcus Reed", avatar: "https://randomuser.me/api/portraits/men/32.jpg", role: "Auto Tech Specialist" },
    category: "Engine Care",
    tags: ["engine", "oil-filter", "maintenance"],
    publishedAt: "2024-10-01T10:00:00Z",
    readTime: 4,
  },
  {
    id: "blog-04",
    title: "Performance Upgrades That Actually Make a Difference",
    slug: "performance-upgrades-that-make-a-difference",
    excerpt: "From cold air intakes to performance exhaust systems — we break down which upgrades deliver real-world results and which ones are just marketing hype.",
    content: "",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=500&fit=crop&q=80",
    author: { id: "auth-03", name: "Jake Torres", avatar: "https://randomuser.me/api/portraits/men/65.jpg", role: "Performance Tuner" },
    category: "Performance",
    tags: ["performance", "upgrades", "tuning"],
    publishedAt: "2024-10-05T10:00:00Z",
    readTime: 8,
  },
];

// ── HERO SLIDES ──────────────────────────────────────────────
export const heroSlides: BannerSlide[] = [
  {
    id: "hero-01",
    headline: "Reliable Parts For Your Car",
    subheadline: "Built To Last.",
    description: "Shop thousands of OEM and aftermarket parts with fast shipping and expert support.",
    cta: "Shop Parts",
    ctaHref: "/shop",
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&h=700&fit=crop&q=85",
    badge: "Free shipping over $75",
  },
  {
    id: "hero-02",
    headline: "Performance You Can Feel",
    subheadline: "Precision Engineered.",
    description: "Upgrade your ride with performance parts designed for maximum power and handling.",
    cta: "Explore Performance",
    ctaHref: "/shop?tag=performance",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&h=700&fit=crop&q=85",
    badge: "Up to 30% off",
  },
];

// ── FREQUENTLY BOUGHT TOGETHER ───────────────────────────────
export const frequentlyBoughtTogether = [
  [products[0], products[4], products[2]],  // Brake combo
  [products[1], products[5], products[11]], // Engine maintenance
];

// ── FEATURED PRODUCTS ────────────────────────────────────────
export const featuredProducts = products.filter((p) => p.isFeatured);

// ── ON SALE PRODUCTS ─────────────────────────────────────────
export const onSaleProducts = products.filter((p) => p.isOnSale);

// ── NEW ARRIVALS ─────────────────────────────────────────────
export const newArrivals = products.filter((p) => p.isNew);
